apiVersion: apps/v1
kind: Deployment
metadata:
 name: <project_id>
 namespace: staging
 labels:
   app: <project_id> #create deployment with label name
   commit-hash: "<VERSION>"
spec:
 replicas: 1
 selector:
   matchLabels:
     app: <project_id>-pods #target pods with this label
 template:
   metadata:
     labels:
       app: <project_id>-pods #create pods with label name
   spec:
     containers:
       - name: <project_id>-cont
         image: <IMAGE_NAME>
         imagePullPolicy: Always
         ports:
           - containerPort: <PORT>
         envFrom:
           - secretRef:
              name: <project_id>.env
              optional: true
              
---
apiVersion: v1
kind: Service
metadata:
  name: <project_id>
  namespace: staging
  labels:
   app: <project_id> #create services with label name
   commit-hash: "<VERSION>"
spec:
  selector:
    app: <project_id>-pods #targeting service name
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: <PORT>
