# script/k8s/ingress.yml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fdc-gateway
  namespace: fdc
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# Service auth
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fdc-auth
  namespace: fdc
spec:
  hosts:
  - "istio-fdc.aegis.antrein.com"
  gateways:
  - fdc-gateway
  http:
  - route:
    - destination:
        host: hello.fdc.svc.cluster.local
        port:
          number: 8000
---
# Service redirect
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fdc
  namespace: fdc
spec:
  hosts:
  - "*"
  gateways:
  - fdc-gateway
  http:
  - route:
    - destination:
        host: fdc-svc.fdc.svc.cluster.local
        port:
          number: 8000
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: ingress-jwt
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.21/security/tools/jwt/samples/jwks.json"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fdc
  namespace: fdc
spec:
  hosts:
  - "*"
  gateways:
  - fdc-gateway
  http:
  - match:
    - uri:
        prefix: /headers
      headers:
        "@request.auth.claims.groups":
          exact: group1
    route:
    - destination:
        port:
          number: 8000
        host: fdc