apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: <project_id>
data:
  default.conf.template: |
    server {
        listen 127.0.0.1:80;
        server_name ${HOST};

        location / {
            proxy_pass ${TARGET_SERVICE};
            proxy_set_header Host ${TARGET_HOST};
            proxy_redirect off;
            proxy_ssl_server_name on;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: <project_id>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      initContainers:
      - name: init-nginx-config
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          mkdir -p /etc/nginx/conf.d && \
          sed -e 's|${HOST}|localhost|g' \
              -e 's|${TARGET_SERVICE}|https://<project_domain>/|g' \
              -e 's|${TARGET_HOST}|<project_domain>|g' \
              /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/templates
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      - name: gateway-proxy
        image: reyshazni/gateway-proxy-production
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_SERVICE_URL
          value: "http://localhost:80"
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  namespace: <project_id>
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: nginx-reverse-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 3M
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: $http_origin";
      # add_header Access-Control-Allow-Origin $http_origin;
      add_header Access-Control-Allow-Methods "PUT,POST, GET, OPTIONS, PATCH";
      more_set_headers "Access-Control-Allow-Credentials: true";
      more_set_headers "Access-Control-Expose-Headers: *";
      add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin,econolab-uid-authorization,authorization,authorization-v2,api-key,base-url,method,path";    
  name: reverse-proxy
  namespace: <project_id>
spec:
  ingressClassName: nginx
  rules:
  rules:
  - host: <project_id>-redirect.antrein.com
    http:
      paths:
      - path: <url_path>
        pathType: Prefix
        backend:
          service:
            name: reverse-proxy
            port:
              number: 8080
  tls:
  - hosts:
    - <project_id>-redirect.antrein.com
    secretName: <project_id>-redirect-tls